---
name: Update APIs

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
  #schedule:
  #- cron: "*/15 * * * *"

jobs:
  build:
    name: Update APIs
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      
      - name: Check out my other private repo
        uses: actions/checkout@v2
        with:
          repository: external-secrets/external-secrets
          path: lib
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Sync Packages
        run: |
          pushd lib
            git checkout ${{ github.event.inputs.version }}
          popd

          cp -fR lib/apis/externalsecrets apis
          cp -fR lib/apis/meta apis

          TESTS=$(find apis -name '*_test.go')
          for TEST in $TESTS; do
            rm $TEST
          done
          rm -fr lib

          find apis -name '*.go' | xargs -0 sed -i 's|github.com/external-secrets/external-secrets|github.com/garethjevans/external-secrets-api|g'
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Update Go Mods
        run: |
          go mod tidy

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'chore(docs): regenerated apis'
          signoff: false
          title: 'chore(docs): regenerated apis'
          token: ${{ secrets.GH_PAT }}
